### ISSUE TITLE
[Bug] Logo shows up too big

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/theme-coreuiv4#8]
# Bug report

### What I did

- installed the v6 demo (alpha): https://github.com/Laravel-Backpack/demo/pull/453
- change `config/backpack/ui.php` to use `theme-coreuiv4`
- opened the dashboard

### What I expected to happen

- look good

### What happened

- looks good except for the logo, which is waaay too big:

![CleanShot 2023-05-08 at 10 58 32](https://user-images.githubusercontent.com/1032474/236768932-53b19d8f-cad5-475b-a159-0c87828b0be2.png)

**Comment by maurohmartinez** [comment]
Uff... yeah, there is a little bit of css that should be removed from `resources/assets/css/style.css:436` in **Tabler**, and added somewhere on demo repo for this to work across themes.

```css
/*Logo*/
.project-logo {
    max-width: 150px;
    height: auto;
}

.auth-logo-container .project-logo {
    max-width: 230px;
    height: auto;
}
```
